# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image1',
            field=models.ImageField(blank=True, height_field=1000, upload_to='media/', width_field=1000),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image2',
            field=models.ImageField(blank=True, height_field=1000, upload_to='media/s', width_field=1000),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('1', 'Baja'), ('2', 'Normal'), ('3', 'Importante'), ('4', 'Urgente')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('n', 'Nueva'), ('a', 'Solucionada'), ('d', 'Desarrollo'), ('r', 'Rechazada')], default='n', max_length=1),
        ),
        migrations.DeleteModel(
            name='StatusIssue',
        ),
    ]
