# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0005_auto_20160915_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bugtracker.StatusIssue'),
        ),
    ]
