# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0007_auto_20160916_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_issue', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunSQL(
            "INSERT INTO bugtracker_categoryissue (id, category_issue) VALUES (1, 'General');"
        ),
        migrations.AlterField(
            model_name='issue',
            name='image1',
            field=models.ImageField(blank=True, max_length=1500, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image2',
            field=models.ImageField(blank=True, max_length=1500, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='category_issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bugtracker.CategoryIssue'),
            preserve_default=False,
        ),
    ]
