# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0008_auto_20160928_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunSQL(
            "INSERT INTO bugtracker_osissue (id, os) "
            "VALUES (1, 'Todos');"
        ),
        migrations.CreateModel(
            name='ReproducibilityIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reproducibility', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunSQL(
            "INSERT INTO bugtracker_reproducibilityissue (id, reproducibility) "
            "VALUES (1, 'Siempre'), (2, 'A veces'), (3, 'Una vez'), (4, 'No aplica');"
        ),
        migrations.AddField(
            model_name='issue',
            name='steps_to_reproduce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='os',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bugtracker.OsIssue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='reproducibility_issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bugtracker.ReproducibilityIssue'),
            preserve_default=False,
        ),
    ]
