# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0010_issue_evaluation_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cellphone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='extension',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
