# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0011_auto_20161005_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='browserissue',
            name='fa_icon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='osissue',
            name='fa_icon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='priorityissue',
            name='bg_color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='priorityissue',
            name='fa_icon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='statusissue',
            name='fa_icon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='typeissue',
            name='fa_icon',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
