# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0012_auto_20161007_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusissue',
            name='show_in_main_list',
            field=models.BooleanField(default=True),
        ),
    ]
