# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-27 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker', '0015_evaluationcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField(blank=True, null=True)),
                ('time_evaluation', models.TextField()),
                ('resolve', models.TextField()),
                ('difficulty', models.TextField()),
                ('contact', models.TextField()),
                ('satisfaction', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EvalIssue', to='bugtracker.Issue')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EvalUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_view_results_evaluations', 'Can view evaluations results'),),
            },
        ),
        migrations.AlterField(
            model_name='evaluationcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Evaluator', to=settings.AUTH_USER_MODEL),
        ),
    ]
