# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-02 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0016_auto_20171020_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueevaluation',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issueevaluation',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
