# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-27 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0016_auto_20171127_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueevaluation',
            name='observations',
        ),
    ]
