# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-02 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0017_auto_20171102_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issueevaluation',
            options={'permissions': (('can_view_results_evaluations', 'Ver resultados Evaluaciones'),)},
        ),
    ]
