# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-02 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0018_auto_20171102_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issueevaluation',
            options={'permissions': (('can_view_results_evaluations', 'Can view evaluations results'),)},
        ),
    ]
