# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-12 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0018_auto_20171127_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
