# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0019_issue_evaluated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='browserissue',
            options={'ordering': ('browser',)},
        ),
        migrations.AlterModelOptions(
            name='categoryissue',
            options={'ordering': ('category_issue',)},
        ),
        migrations.AlterModelOptions(
            name='headquarter',
            options={'ordering': ('headquarter',)},
        ),
        migrations.AlterModelOptions(
            name='osissue',
            options={'ordering': ('os',)},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('user__first_name',)},
        ),
        migrations.AlterModelOptions(
            name='priorityissue',
            options={'ordering': ('priority',)},
        ),
        migrations.AlterModelOptions(
            name='reproducibilityissue',
            options={'ordering': ('reproducibility',)},
        ),
        migrations.AlterModelOptions(
            name='softwareissue',
            options={'ordering': ('software',)},
        ),
        migrations.AlterModelOptions(
            name='statusissue',
            options={'ordering': ('status',)},
        ),
        migrations.AlterModelOptions(
            name='typeissue',
            options={'ordering': ('type_issue',)},
        ),
        migrations.AddField(
            model_name='person',
            name='dev',
            field=models.BooleanField(default=False),
        ),
    ]
