# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-05 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0020_auto_20180503_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sprint',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
