# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-08 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0021_issue_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusissue',
            name='bg_color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
