# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-07 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0022_auto_20180607_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusissue',
            name='fa_icon',
        ),
        migrations.AlterField(
            model_name='statusissue',
            name='bg_color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
